version: '3.9'
services:
    apache-example:
      container_name: php2
      build: ./php
      depends_on:
        - db2
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html
      networks:
        - network
    
    db2:
      container_name: db2
      image: mysql:5.7
      ports:
        - 3306:3306
      volumes:
       - mysql:/var/lib/mysql
       - ./persons.sql:/docker-entrypoint-initdb.d/persons.sql 
      restart: always
      environment:
        MYSQL_DATABASE: "martindb"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "admin"
        MYSQL_ROOT_PASSWORD: "root"
      networks:
        - network
    
networks:
  network:
    driver: bridge

volumes:
  mysql:
